version: "3.4"

services:
    nginx:
        build:
          context: .
          dockerfile: docker/Nginx.Dockerfile
        ports:
            - 8098:80
        links:
          - php-fpm
        volumes:
            - ./:/var/www/laravel-docker

    php-fpm:
        build:
          context: .
          dockerfile: docker/Php-Fpm.Dockerfile
        volumes:
            - ./:/var/www/laravel-docker
        links:
          - mysql

    mysql:
        image: mysql
        ports:
          - 33061:3306
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=laravel

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
